[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "numrun"
version = "0.2.0"
dependencies = []

[project.scripts]
numrun = "numrun.cli:main"

[tool.setuptools.packages.find]
include = ["numrun*"]
